#ifndef COMMON_H
#define COMMON_H

#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240

#define PI_MESSAGE_COUNT 200
#define DMA_MESSAGE_COUNT 1
#define MAIN_MESSAGE_COUNT 8
#define GAME_MESSAGE_COUNT 1
#define TASK_COUNT 2

#define MEMORY_ALLOCATION_BUFFER_SIZE 0xA000
#define ASCII_FONT_BUFFER_SIZE 0x800
#define OVERLAY_BUFFER_SIZE 0x290000

#endif // COMMON_H
